### ISSUE TITLE
[Bug]: Maps widget is not working on release

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Maps widget is not working on release

On release
![image](https://user-images.githubusercontent.com/79509062/149112262-eee29841-39a3-4423-8079-f5aa96188e0f.png)

On DP:
![image](https://user-images.githubusercontent.com/79509062/149112058-b73e5b82-6358-43da-a75a-73fa7bc1b06e.png)

### Steps To Reproduce

1. Drag and drop maps widget onto canvas and observe

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Hi @ramsaptami, I was unable to reproduce this in release env. Can you help me out?

https://www.loom.com/share/ce3ca13522b14f87a085199383402b10

**Comment by dilippitchika** [comment]
I guess this is fixed by shri now, if yes please close this

**Comment by ramsaptami** [comment]
Reopening this since it's still not working
![image](https://user-images.githubusercontent.com/79509062/149132870-71c039a0-2d34-49a0-a6d3-889e67e082ee.png)

**Comment by sbalaji1192** [comment]
we get this error when there is an issue with the google maps API key.

**Comment by ramsaptami** [comment]
This has been fixed by updating `Content-Security-Policy` header hence closing the issue
