### ISSUE TITLE
[Bug]: Need to refresh the screen to populate date in date picker after I use moment object in Default date

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Date do not populate on date picker widget after using {{moment()}} in edit mode.

### Steps To Reproduce

1. Drag and drop a date picker widget
2. Use {{moment()}} in default date property
3. Observe the date do not populate on the widget
4. Refresh the screen and see that date gets populated

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@vivekverma2312 cannot reproduce, can you check this once?

**Comment by vivekverma2312** [comment]
@dilippitchika Adding loom video for this
https://www.loom.com/share/a9b925d70b9d48da831d6d5b2d75ca50

**Comment by dilippitchika** [comment]
Ok, my bad I checked in production and not release. @sbalaji1192 are the changes in datepicker not in release but in production? Or this looks like a different issue. Please check. 

@vivekverma2312 please make sure this issue is resolved before promoting a release.

**Comment by sbalaji1192** [comment]
@dilippitchika Doesn't seem like caused by the moment changes we did. I reverted my changes, but it is still happening.

**Comment by dilippitchika** [comment]
@sbalaji1192 I am assigning this to @techbhavin to take this forward.
