### ISSUE TITLE
[Bug]-[600]:RichTextEditor not loading at start

### ISSUE THREAD

**Issue by lublak** [appsmithorg/appsmith#11624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently i have a RichTextEditor.
The "default text" is filled by a database.
In widget edit mode (where you can place the appsmith widgets) it works fine.
Now I deploy the app and open it it does not work. The editor remains empty.
If I change the page in the same app via the navigation bar of Appsmith and change back again it works.
It can be a disaster if the editor is empty and when changing the data then the current data is completely deleted from the database (onChange).

### Steps To Reproduce

1. Place a RichTextEditor Widget
2. Use a database query (postgres) `{{RichTextData.data[0].data}}` (`SELECT data FROM RichTextData;`)
3. Deploy
4. Open the deployed app

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@lublak it seems to be working for me. Can you share an app that reproduces this issue?

**Comment by lublak** [comment]
@Nikhil-Nandagopal yes i can. (But i removed the password from the datasource)
[IntranetMenu.zip](https://github.com/appsmithorg/appsmith/files/8184977/IntranetMenu.zip)

**Comment by lublak** [comment]
`{{MenuData.data[0].data}}` is undefined for the first start.
I added just replaced it with `{{MenuData.data[0].data}}test` so a i can see in deployed editor: `undefined`

**Comment by Nikhil-Nandagopal** [comment]
@lublak can you reproduce this with our users db? I tried replacing your query with fetch users and was able to get it to wrok

**Comment by lublak** [comment]
I found the issue @Nikhil-Nandagopal
The iis reverse proxy has blocked the websocket connection.

Interesting then only that appsmith itself continues to run. It would be more practical to lock the entire app in case of a failed connection in order to avoid erroneous data in case of a faulty connection.

**Comment by lublak** [comment]
But after releasing the websocket there is another problem.
What is also problematic here is the delay.
The user can already enter data. The data arrives delayed and is then inserted in the editor.

**Comment by lublak** [comment]
Well the error is not fixed after all, the data is only displayed irregularly. Maybe once every 15 page views.
I have tried the following address because the test user database is unfortunately blocked by our internal network: http://jsonplaceholder.typicode.com/users

**Comment by Nikhil-Nandagopal** [comment]
@lublak what you can do here is disable the RTE if the Query is in a loading state to prevent user inputs till the query returns

**Comment by lublak** [comment]
@Nikhil-Nandagopal just for a info i can reproduce the issue of non loading data also at your app.appsmith site:
https://app.appsmith.com/applications/6225c53e45ea27345b4970f2/pages/6225c53e45ea27345b4970f5

**Comment by lublak** [comment]
> disable the RTE

The thing about protecting because of the delay is a good thing. But unfortunately does not fix the problem that sometimes it is not loaded at all

**Comment by lublak** [comment]
@Nikhil-Nandagopal 
Just a small thought, maybe sometimes the editor was not initialized yet. Possibly by the browser cache it is sometimes initialized faster before the data are there.
The data is sometimes faster and sometimes slower.

```js
editor.on('init', function (e) {
  editor.setContent(content);
});
```

**Comment by Nikhil-Nandagopal** [comment]
@lublak we're now able to reproduce the issue.
You need to open this on Safari and you will be able to see it. To reproduce it, we need to kill the safari desktop app and re-open it

**Comment by dilippitchika** [comment]
Adding an app where this can be reproduced, please check the app in safari
[RTEissue.json.zip](https://github.com/appsmithorg/appsmith/files/8213263/RTEissue.json.zip)

**Comment by lublak** [comment]
@dilippitchika I can't test it in Safari because I don't own an Apple device.
But on firefox: 
![grafik](https://user-images.githubusercontent.com/44057030/157434999-d9a34d8b-0aff-4676-ad95-f334b8cb6d7b.png)

**Comment by dilippitchika** [comment]
Hey @lublak i can see the same issue in safari. Our team can use safari to debug this further.

**Comment by somangshu** [comment]
This seems fixed now, Even in the example attached above, I have tried this in release and Prod envs.

[my app](https://release.app.appsmith.com/applications/615a9cc0b6f33d68bee471d1/pages/615a9cc0b6f33d68bee471d3/edit)

**Comment by dilippitchika** [comment]
@lublak can you check and let us know if this is happening?

**Comment by lublak** [comment]
@dilippitchika For me the error still occurs: https://app.appsmith.com/applications/6225c53e45ea27345b4970f2/pages/6225c53e45ea27345b4970f5

What I notice is that undo is not set when it remains empty and undo is set when the content is successfully loaded.

![HxEyUw47IE](https://user-images.githubusercontent.com/44057030/158779571-3f29cef0-e6ba-443b-b965-65f8d7ec9402.gif)

I have the feeling that setContent is not called. Unfortunately I don't know how cypress is called (setTinyMceContent).

https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/support/commands.js#L2907

**Comment by Nikhil-Nandagopal** [comment]
I can reproduce this on prod as well

**Comment by dilippitchika** [comment]
@vivekverma2312 need some help here, we are able to reproduce this in safari in macbooks but the user reported that this is happening in firefox in a different OS. 

Can we ask someone to check this across browsers and OS and help us with a report before we start triaging this?

**Comment by vivekverma2312** [comment]
@Tooluloope Able to repro the issue on Windows (Chrome & Firefox)
The data is not populating on RTE after deployment. If we change the page in view mode then the data starts populating. 
https://loom.com/share/50bcab3eacc84aefb7711d3621ca6dbc

**Comment by dilippitchika** [comment]
@vivekverma2312 is this happening anywhere else in mac? Or we only checked windows?

@somangshu whom can we assign this to? I believe this is clearly reproducible in windows machines.

**Comment by somangshu** [comment]
This is happening on windows and as said above and also on safari on mac. @techbhavin please triage to identify the problem here

**Comment by dilippitchika** [comment]
Reach - 158 in 6 months
Impact - High

**Comment by dilippitchika** [comment]
Above estimate is just to rank better, not a real estimate yet
