### ISSUE TITLE
[Bug]: Text widget - Overflow options still works in Auto height - even though Option is hidden in property pane

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we D&D a Text widget and choose Scroll contents or Truncate text, and choose Auto height in Height property, we are still able to see scroll contents and Truncate text works.

https://user-images.githubusercontent.com/104895602/191777233-94f674ea-aa68-40cf-8614-b3896ae0643c.mp4

### Steps To Reproduce

1. D&D a text widget
2. Choose Scroll contents or Truncate text in Overflow text property
3. Choose Auto height in Height property
4. Observe Overflow text property is hidden
5. Observe scroll is still enabled when Scroll contents was chosen before
6. OR Delete some text from the widget and Observe Truncate text is still available

### Version

Deploy preview

**Comment by ankurrsinghal** [comment]
The issue has been resolved here, https://github.com/appsmithorg/appsmith/pull/17054

**Comment by Sripriya93** [comment]
We are still facing this issue, please check the loom, verified in the latest DP and also in the given DP, Moving to Inprogress

https://images.zenhubusercontent.com/275993885/5d432e96-2bdd-40c9-8f41-b74364c03b5b/dp___28_9___editor___appsmith___28_september_2022.mp4

**Comment by Sripriya93** [comment]
Have tested the same in latest DP, working fine, moving to done
