### ISSUE TITLE
[Bug]: Unable to start Appsmith after auto update (MongoDB cannot start)

### ISSUE THREAD

**Issue by WillemJann** [appsmithorg/appsmith#19542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the update of Appsmith yesterday, my deployment does not work anymore. I get a 404 error when I try to reach Appsmith in the browser (https://appsmith.perfectxl.com). I think it is related to the upgrade of the MongoDB instance to v5.0.14.

This is my `docker-compose.yml` file:

```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    expose:
      - "80"
      - "443"
      - "9001"
    volumes:
      - ./stacks:/appsmith-stacks
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.appsmith.entrypoints=websecure"
      - "traefik.http.routers.appsmith.rule=Host(`appsmith.perfectxl.com`)"
      - "traefik.http.routers.appsmith.service=appsmith-service"
      - "traefik.http.services.appsmith-service.loadbalancer.server.port=80"
    restart: unless-stopped

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped

networks:
  traefik:
    external: true
```

### Steps To Reproduce

1. The status of docker is as follows:

```
root@docker:~/appsmith# docker-compose ps
         Name                       Command                   State                  Ports
----------------------------------------------------------------------------------------------------
appsmith                 /opt/appsmith/entrypoint.s ...   Up (unhealthy)   443/tcp, 80/tcp, 9001/tcp
appsmith_auto_update_1   /watchtower --schedule 0 0 ...   Up
```

2. The status of the supervisor is as follows:

```
root@docker:~/appsmith# docker-compose exec appsmith supervisorctl status
backend                          RUNNING   pid 1338, uptime 0:16:05
cron                             RUNNING   pid 1340, uptime 0:16:05
editor                           RUNNING   pid 1339, uptime 0:16:05
mongodb                          FATAL     Exited too quickly (process log may have details)
redis                            RUNNING   pid 1335, uptime 0:16:05
rts                              RUNNING   pid 1337, uptime 0:16:05
stdout                           RUNNING   pid 1334, uptime 0:16:05
```

3. This is the output when I try to start mongodb with the supervisor:

```
root@docker:~/appsmith# docker-compose exec appsmith supervisorctl start mongodb
mongodb: ERROR (spawn error)
```

4. This is what I get when I try to start mongodb manually: (based on [this template](https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/templates/supervisord/mongodb.conf))

```
root@docker:~/appsmith# docker-compose exec appsmith bash
root@7d9941061565:/opt/appsmith# cd /appsmith-stacks/data/mongodb/
root@7d9941061565:/appsmith-stacks/data/mongodb# mongod --port 27017 --dbpath . --logpath /appsmith-stacks/logs/mongodb/db.log --replSet mr1 --keyFile /mongodb-key --bind_ip localhost
Illegal instruction (core dumped)
```

Do you have any suggestion to fix this deployment issue? What can I do to get Appsmith up and running?

If you need more information, let me know.

### Version

Self Hosted - latest Docker version (v1.9.1?)

**Comment by pranavkanade** [comment]
We've fixed the issue. Please upgrade to v1.9.2

**Comment by WillemJann** [comment]
I've upgraded to v1.9.2:

```
root@docker:~/appsmith# docker-compose pull
Pulling appsmith    ... done
Pulling auto_update ... done

root@docker:~/appsmith# docker-compose up --detach
Recreating appsmith ... done
```

Unfortunately, the issue has not been fixed. I still get a 404 error, and the status of MongoDB is the same:

```
root@docker:~/appsmith# docker-compose exec appsmith supervisorctl status
backend                          RUNNING   pid 1338, uptime 0:01:24
cron                             RUNNING   pid 1340, uptime 0:01:24
editor                           RUNNING   pid 1339, uptime 0:01:24
mongodb                          FATAL     Exited too quickly (process log may have details)
redis                            RUNNING   pid 1335, uptime 0:01:24
rts                              RUNNING   pid 1337, uptime 0:01:24
stdout                           RUNNING   pid 1334, uptime 0:01:24
```

Maybe the newer MongoDB version is not compatible with our Docker environment? That's what I suspect because of the error message "Illegal instruction (core dumped)". See all error details in the first post, everything under "Steps To Reproduce" still applies with the latest version.

Let me know if I can provide more information.

**Comment by interessante-projekte** [comment]
hello willemjann, 
i downgraded to v1.8.14.1 (18 days old) and it is working (for me). apps import without a problem.

**Comment by WillemJann** [comment]
Downgrading to v1.8.15 resolved the issue. I changed the image to `index.docker.io/appsmith/appsmith-ce:v1.8.15` in `docker-compose.yml` and recreated the docker instance. After a few mintues Appsmith was up and running.

So there is an incompatibility with MongoDB v5.0.14. Because we use the docker image without mongo installed separately, it does not work starting from Appsmith v1.9.0.

Same issue here: https://community.appsmith.com/t/error-503-on-selfhosted-after-watchtower-automatic-update-to-v1-90/1835

**Comment by baqirvd** [comment]
Can someone help me with the steps to downgrade appsmith? I want to downgrade from v1.9.3.1 to v.1.9.2

**Comment by pranavkanade** [comment]
more info - https://discord.com/channels/725602949748752515/1065213213815353395

**Comment by liebig** [comment]
Problem solved by the AppSmith Discord post by the following step:

> Are you upgrading your instance from version < v1.9.2 to  > v1.9.3?
   If yes, then first upgrade to v1.9.2 first and then upgrade to the latest version.

And if that still does not work
> If you're still reading, that means you have a single container setup, and even though you're on v1.9.2 you're still getting 503.
    This could mean your machine does not support mongoV5. A couple of symptoms are listed below:
        You can check if the appsmith container is unhealthy.
        The list of supported processors is listed here - https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX.
        Server logs have an error like - Exception in monitor thread while connecting to server localhost:27017
    Solution: Upgrade your machines to CPUs that support Mongo V5. If you can't, unfortunately, you'll have to revert to the older version.  For now, you can only upgrade till v1.8.15.
        You can do this by changing the appsmith-ce to appsmith-ce:v1.8.15 in your installation/upgrade steps

For me the problem was actually that in my virtual machine the CPU extension AVX was not enabled!
I hope this helps one or the other :)
