### ISSUE TITLE
[Bug]: Hyperlink with Underscore at the End Placed Inside Text Widget Does Not Include the Underscore

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#19736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a URL ends in an underscore (e.g. “https://test.com/abcfe_”), the hyperlink that results from using the string in a Text widget does not include the underscore.
![image](https://user-images.githubusercontent.com/101268423/211808099-e0fd91e1-2023-4124-b04e-7319de7270b4.png)

Workaround:
![image](https://user-images.githubusercontent.com/101268423/211808189-bdc354b7-1c88-4d34-a7ca-770f649d5376.png)
However, this workaround is not optimal, as users end up writing lengthy javascript with lots of concats.

### Steps To Reproduce

1. Add a Text widget to the canvas.
2. In the Text property, type a hyperlink that contains an underscore at the end.
3. Note that when hovering over the hyperlink, the underscore does not get included.

### Version

Appsmith v1.8.16-SNAPSHOT

**Comment by somangshu** [comment]
Internally the package we use in text widget to parse the URL has [the problem](https://github.com/milesj/interweave/issues/120)
Its said that this is fixed in the next version, we need to check if upgrading the package fixes our problem and if it has other impact any where else

**Comment by somangshu** [comment]
Setting this to medium priority as a very easy workaround exist

**Comment by vsvamsi1** [comment]
I have updated the packages and it still persists. I have raised the issue with the author. 
https://github.com/milesj/interweave/issues/120#issuecomment-1396487236

**Comment by raushan3737** [comment]
Hi  @ame-appsmith  @somangshu : I would like to work on this issue.

**Comment by daaliachhak17** [comment]
created jira ticket-https://zemoso.atlassian.net/browse/TNOSB-414

**Comment by raushan3737** [comment]
Hi @somangshu , @ame-appsmith: I have debugged the code and found that the latest release of interweave library also has not the support to contain the `_` at the end of the url.

If we want to have the support of underscore(_) may be we have to use another js library that will have alot of changes. 

**Checked with the below version:** 
```
"interweave": "^13.1.0",
"interweave-autolink": "^5.1.1" 
```

**Comment by Nikhil-Nandagopal** [comment]
@raushan3737 we can skip this issue is not that important and the solve looks complicated
