### ISSUE TITLE
[Bug] - Mongo DB - old values retained in manage environments when the DS is deleted

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20025]
On creating a datasource, adding variables in manage environments, I faced an error which blocked me. 
I tried deleting the DS, and tried to create a new DS, and set manage environments again
I note that old values are still retained in the Manage environments field

Video depicting the issue -

https://ddpa7mfuvv.vmaker.com/record/mkR2ek0pCEUtWKa9

**Comment by ayushpahwa** [comment]
Fixed and raised fix to DP

**Comment by btsgh** [comment]
This is still reproducible. Video is [here](https://ddpa7mfuvv.vmaker.com/record/LgG6grwPri7moaAO)

**Comment by ayushpahwa** [comment]
This will be fixed with the ds rename issue @btsgh 2
