### ISSUE TITLE
[Bug]: Elastic search: After having configured staging also through Manage env, there are no values on review page

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="ES" src="https://user-images.githubusercontent.com/119847783/217712928-13901d40-f729-48b1-a026-d9228540fbbb.png">
Elastic search: After having configured staging also through Manage env, there are no values on review page

### Steps To Reproduce

Precondition - Assume prod is the default env

1. Create new Elastic search datasource
2. Configure staging
Observe - On the review page, there are no values

### Version

1.9.6

**Comment by ayushpahwa** [comment]
I think you have not provided value for the host address and port. @AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here?

**Comment by AnandShahs123** [comment]
Off course, I have provided. you just need to follow the steps and it can be reproduced @ayushpahwa

**Comment by ayushpahwa** [comment]
![image.png](https://images.zenhubusercontent.com/60d04e24be9e2f34b7493dfb/45bd32d8-e8b4-4893-bcb2-2834d54e3ae1)
Attaching screenshot from production. If we do not add value to host address and port, there is no value to be shown that is not sensitive. @sribalajig can you please take a look.

**Comment by sribalajig** [comment]
@btsgh @AnandShahs123 this is not a regression issue for multiple environments. We should solve it but not as part of this porject.

**Comment by AnandShahs123** [comment]
as discussed again, this is a ME issue @ayushpahwa @sribalajig

**Comment by btsgh** [comment]
This is still not fixed. I cannot see anything on the review page even after configuring prod and staging on elastic search. Screenshots attached below - 

![MEESReviewPage1.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/c7975c27-b4de-4780-9431-7a119fbc88c8)
![MEESReviewPage2.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/39d470af-f353-47b2-b012-e3c7dbe10b56)
![MEESReviewPage3.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/67cdfafb-c326-4b1d-bab6-9fad93d9d094)

**Comment by btsgh** [comment]
This is still not fixed. I cannot see anything on the review page even after configuring prod and staging on elastic search. Screenshots attached below - 

![MEESReviewPage1.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/c7975c27-b4de-4780-9431-7a119fbc88c8)
![MEESReviewPage2.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/39d470af-f353-47b2-b012-e3c7dbe10b56)
![MEESReviewPage3.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/67cdfafb-c326-4b1d-bab6-9fad93d9d094)
