### ISSUE TITLE
[Bug]: Scroll bar is not coming in container when contentoverflows

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Scroll bar is not coming in container when content  overflows

### Steps To Reproduce

https://www.loom.com/share/b78e6eddd2e54ad6b17cbd71d1f95723

### Version

DP

**Comment by marks0351** [comment]
@kamakshibhat-appsmith is this happening only in auto layout?

**Comment by kamakshibhat-appsmith** [comment]
@marks0351 yes correct. I fixed layout, its working as expected

**Comment by Sripriya93** [comment]
Issue still exists in [DP](https://ce-20836.dp.appsmith.com/). Moving to reopen. @marks0351
