### ISSUE TITLE
[Bug] The empty value when binding an Input / Text widget should be an empty string not undefined

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2785]
## Description

The empty value for all string bindings should return an empty string

### Steps to reproduce the behavior:
1. Drag an Input Widget
2. Drag a text widget
3. Bind the text property to the input {{Input1.text + ""}}
4. See it shows undefined, it should show an empty string
5. Change the binding to {{Input1.text}} it shows empty string. This is odd because it should show undefined here
6. Drag a Query and bind {{Input1.text}} in the query
7. See that undefined is sent to the query

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @mohanarpit another inconsistent binding issue

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal This is resolved in the PR: #2687. This fix is currently in our release branch and will be available on the `master` branch soon.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit I checked release and this is not fixed on it so I'm re-opening

**Comment by mohanarpit** [comment]
Sorry, I forgot to mention in my previous message. The following is an incorrect assumption

> * Bind the text property to the input {{Input1.text + ""}}
> 
> * See it shows undefined, it should show an empty string

This is because JS will treat `undefined` as a string when concatenated with another string. That is why you will see `undefined` is printed in the text box instead of an empty invalid value. 

Apart from this, is there any other use-case from the one listed above that is not working as expected in the release branch? I just went through each of the use-cases and the results were as expected.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit I understand why it is showing undefined when I concatenate it but if the argument is that because it is undefined so no value is being shown in the Text, then the same should be true of SQL where if I send
select * from users where name ilike '%{{Input1.text}}%', it should send 
select * from users where name ilike '%%' if the Input is empty but that is not the case either

**Comment by mohanarpit** [comment]
Again, this is a JS thing. The text widget is being sent the value `undefined` which is causing the `TextComponent` to not render anything. On the other hand, when we replace this in SQL, API actions etc they take the value as-is. Hence, you see that the value `undefined` is being passed to the query/API. 

What you are suggesting is to replace `undefined` with an empty string. But that wouldn't be correct and would be harder to reason with within the Appsmith platform.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit what I am suggesting is to handle this as part of the plugin-specific substitution where undefined values are not substituted anywhere. 
Undefined is not an unassigned value unlike null and should not be substituted in any case regardless

**Comment by Nikhil-Nandagopal** [comment]
Closing as this is not a problem with prepared statements
