### ISSUE TITLE
[Bug] Table height in view mode does not match container

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2924]
## Description

Placing a table and a container side by side in view mode do not match in height
<img width="1229" alt="Screenshot 2021-02-09 at 11 46 57 AM" src="https://user-images.githubusercontent.com/3897254/107323928-2534f680-6acd-11eb-90a0-a63c4bde671d.png">

**Comment by marks0351** [comment]
@Nikhil-Nandagopal this issue seems to have been resolved. ![Screenshot 2021-03-19 at 10.17.25 AM.png](https://images.zenhubusercontent.com/6041f3b8ac4b18f94944edfc/6e8e155e-e54e-4bca-8285-81718e5e0855)

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 I still see it on prod and release

https://user-images.githubusercontent.com/3897254/111737298-5c08e400-88a5-11eb-9af9-39f89702a006.mov
