### ISSUE TITLE
[Bug]: In split pane view, for gsheets queries, Bind Data, Documentation and Results: Records text get cutoff. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I view a gsheet query in the split pane mode, Bind Data, Documentation and Results: Records text get cutoff. 

### Steps To Reproduce

<img width="127" alt="Screenshot 2024-02-29 at 4 30 06 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/62ead258-cda5-45bb-ab8d-58d7e8951a9a">

https://github.com/appsmithorg/appsmith/assets/101863839/e4d5ffc0-859c-4d6c-94e7-cf3579735bf1

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=be85704c57fd40a5904a0c5dc870cc41&pm=s

**Comment by hetunandu** [comment]
fixed in https://github.com/appsmithorg/appsmith/commit/3c59066b893e8ac9a997f5659a019c5f2c2963f1

**Comment by btsgh** [comment]
Still seeing issue on latest release. [Trying this on 15 march 11 AM]

https://github.com/appsmithorg/appsmith/assets/101863839/242e5e40-018b-4734-990b-37c506dd3a65

This is quite specific to Gsheets - it works fine for other datasource queries. Please refer above video for clarity

**Comment by hetunandu** [comment]
@btsgh Could you test this with 100% zoom level. This is only reproducible on my end when zoom is applied (110% or higher)

**Comment by btsgh** [comment]
So at 100% zoom level, though the bind data and documentation don't get cutoff, they move closer to the border and the close icon is touching the border. This does not feel right. The placement of these text/links and icons should be consistent across queries of various DS.

https://github.com/appsmithorg/appsmith/assets/101863839/aaf6d38a-7996-48c6-94cd-273c956d648e
