### ISSUE TITLE
[Bug] File uploads bigger than 10MB fails.

### ISSUE THREAD

**Issue by mosinuga** [appsmithorg/appsmith#3704]
## Description

[What happened]
Uploading file size of more than 10mb fails

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Upload file size that is more than 10mb
2. See error on the internal-appsmith-server
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 5242880

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by areyabhishek** [comment]
We currently limit file sizes to 10mb on NGINX. You can increase file size limit on NGINX docker image by increasing the number in client_max_body_size 10m;
We have an incoming fix that increases the size to 100mb. https://github.com/appsmithorg/appsmith/pull/3553

**Comment by mosinuga** [comment]
Thank you for your response. I've changed the limit on the nginx, but the error above is coming from the internal-server

**Comment by mosinuga** [comment]
This is the complete error message (I'd tried to play with some java options, but it didn't resolve it):
`appsmith-internal-server_1_6fbbe4576acd | org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 5242880
appsmith-internal-server_1_6fbbe4576acd |       at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:101)
appsmith-internal-server_1_6fbbe4576acd |       at org.springframework.core.io.buffer.LimitedDataBufferList.updateCount(LimitedDataBufferList.java:94)
appsmith-internal-server_1_6fbbe4576acd |       at org.springframework.core.io.buffer.LimitedDataBufferList.add(LimitedDataBufferList.java:59)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.MonoCollect$CollectSubscriber.onNext(MonoCollect.java:132)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:218)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:484)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:211)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-internal-server_1_6fbbe4576acd |       at java.base/java.lang.Thread.run(Unknown Source)
nginx_1_f99fa97097a4        | "25/Mar/2021:17:15:16 +0000" client=10.0.2.2 method=POST request="POST /api/v1/actions/execute HTTP/1.1" request_length=20647788 status=500 bytes_sent=857 body_bytes_sent=128 referer=http://localhost/applications/603659be409488541c467886/pages/603659be409488541c467888 http_x_forwarded_for=- user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" upstream_addr=172.19.0.5:8080 upstream_status=500 request_time=1.027 upstream_response_time=0.524 upstream_connect_time=0.000 upstream_header_time=0.524
appsmith-internal-server_1_6fbbe4576acd |  - Operator called default onErrorDropped
appsmith-internal-server_1_6fbbe4576acd | io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:92)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:222)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:484)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:211)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-internal-server_1_6fbbe4576acd |       at java.base/java.lang.Thread.run(Unknown Source)
appsmith-internal-server_1_6fbbe4576acd |  - Failed to release a message: DefaultHttpContent(data: PooledSlicedByteBuf(freed), decoderResult: success)
appsmith-internal-server_1_6fbbe4576acd | io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:92)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:109)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:211)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-internal-server_1_6fbbe4576acd |       at java.base/java.lang.Thread.run(Unknown Source)
appsmith-internal-server_1_6fbbe4576acd |  - [id: 0x60920430, L:/172.19.0.5:8080 ! R:/172.19.0.6:49328] Error was received while reading the incoming data. The connection will be closed.
appsmith-internal-server_1_6fbbe4576acd | reactor.core.Exceptions$BubblingException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.Exceptions.bubble(Exceptions.java:170)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.Operators.onErrorDropped(Operators.java:521)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.MonoCollect$CollectSubscriber.onError(MonoCollect.java:144)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:416)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:227)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:484)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:211)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-internal-server_1_6fbbe4576acd |       at java.base/java.lang.Thread.run(Unknown Source)
appsmith-internal-server_1_6fbbe4576acd | Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:92)
appsmith-internal-server_1_6fbbe4576acd |       at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
appsmith-internal-server_1_6fbbe4576acd |       at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:222)
appsmith-internal-server_1_6fbbe4576acd |       ... 33 common frames omitted`

**Comment by nidhi-nair** [comment]
@mosinuga We have raised the default value of the maximum payload size that our server accepts to 100MB. This change will be part of the next release. You will also have the option to configure this default via an environment variable `APPSMITH_CODEC_SIZE` using the instructions given [here](https://docs.appsmith.com/v/v1.2.1/setup/docker#enabling-services-for-self-hosting).

**Comment by mosinuga** [comment]
Thank you for your quick response. Very appreciated. Btw, is this streaming now or still buffering in memory?

**Comment by nidhi-nair** [comment]
For now, this change only increase the in-memory limit. We will be shipping a more comprehensive solution to stream request payloads soon. :)

**Comment by mosinuga** [comment]
Great - thank you.

**Comment by mosinuga** [comment]
Is this feature going to be in 1.4.5? When is it scheduled to be released?

**Comment by nidhi-nair** [comment]
Hey @mosinuga! This change is a part of [v1.4.5](https://github.com/appsmithorg/appsmith/releases/tag/v1.4.5). We just released it today, you should be able to use requests with larger request or response sizes after this update.

**Comment by mosinuga** [comment]
Thank you - I have been able to pull the new image.

**Comment by bernardworthy** [comment]
Hi there. I'm still seeing this Error Message on GET requests for response data that is larger than 10MB. Perhaps this Stack Overflow Answer is the trick? https://stackoverflow.com/a/59392022/4151472

**Comment by mosinuga** [comment]
@bernardworthy Have you pulled the latest image (1.4.5)?

**Comment by nidhi-nair** [comment]
@bernardworthy Apart from what @mosinuga mentioned, could you give me details of your installation? You might need a manual restart of the server image if this is on docker.

**Comment by mosinuga** [comment]
There are two things we have observed with v1.4.5:

1. It is backward incompatible: having rolled to v1.4.5, going back to v1.4.3 broke our application.
2. More importantly, v1.4.5 is significantly slower.
Can these be further investigated?

**Comment by bernardworthy** [comment]
@mosinuga @nidhi-nair I'm just using the Appsmith hosted version and attempting to perform a GET request on a JSON file url that is larger than 10MB.

**Comment by mosinuga** [comment]
Okay - has the hosted version been updated to v1.4.5 @nidhi-nair?

**Comment by mosinuga** [comment]
Mine actually shows 1.4.5 - so @nidhi-nair should be able to help you out.

**Comment by mosinuga** [comment]
![image](https://user-images.githubusercontent.com/43381160/112980064-4ae78f00-9151-11eb-9bc7-964ee460d3d6.png)
@bernardworthy It says hosted version will continue with a limit of 10mb

**Comment by nidhi-nair** [comment]
@mosinuga Could you please let me know what parts of the application have slowed down/broken for you?

@bernardworthy The cloud hosted version for Appsmith continues to have the 10MB limit, since we see a lot of traffic on the cloud. We'll be able to support a larger file size once we introduce streaming.

**Comment by bernardworthy** [comment]
Understood. Thanks @nidhi-nair @mosinuga!

**Comment by mosinuga** [comment]
@nidhi-nair The entire application has slowed down. I noticed that it seems to be doing so many analytics...
[appsmith.zip](https://github.com/appsmithorg/appsmith/files/6228580/appsmith.zip)

**Comment by nidhi-nair** [comment]
@mosinuga From a preliminary look at some of your network activity, I see that a major chunk of this time is spent waiting, especially for actions. It is possible that these actions are actually dealing with huge file sizes and hence slowing the application down.

The following request, for example, should shed some light on the cause:
`https://appsmith.test.apps.wsp-lattice.io/api/v1/actions/view?applicationId=603659fa409488541c467889`

Could you please check to see if this action does in fact have a large payload?

**Comment by mosinuga** [comment]
I'll check - why we thought it must be due to the upgrade was the fact that the speed was fine until yesterday when we upgraded to v1.4.5. And this is not only when payload is involved - just clicking through the application in general has slowed down. Have you noticed any difference in speed on your side?

**Comment by nidhi-nair** [comment]
@mosinuga We have had one team member experience issues with the API pane editor recently, and are currently investigating the same. I have opened another issue (https://github.com/appsmithorg/appsmith/issues/3772) to track this degradation, let's move over to that thread with your findings.

**Comment by mosinuga** [comment]
Yes, that's a good idea to track it in #3772. It seems to be a request made to load the current app, which is what significantly takes longer now. Once the first page of the app is loaded, everything seems normal like before
