### ISSUE TITLE
[Bug] Unable to delete datasource even if all the applications in organisation are deleted 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4609]
## Description

After deleting all the application in an organisation it's expected that datasources should not be attached with any action, but trying to delete datasources throws error : _(Cannot delete datasource since it has 1 action(s) using it.)_ 

### Steps to reproduce the behaviour:

1. Create new org
2. Create new application
3. Create DS (Created DB query using mongoDB as datasource)
4. Deleted the application so now there isn’t any application present
5. Create new application without any widget and actions
6. Try to delete the datasource

**Comment by Nikhil-Nandagopal** [comment]
This is beacause deleting an app / page doesn't mark the datasource as deleted

**Comment by abhvsn** [comment]
I think this has been fixed. Earlier even if you don't have any action associated with the datasource user was not able to delete the datasource.

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn this is not fixed. When we delete an app/page, the action is not marked as deleted. So this remains in a bad state

**Comment by sharat87** [comment]
Changed priority to High as this is impacting users and has no workaround today.

**Comment by RakshaKShetty** [comment]
The issue can be reproducible in the below scenario, so reopening the bug 
The scenario is to create a new organization, called org1.
Create an application in this, called app1.
Create a datasource called ds1(create query1), Now delete the app1
Now create another application in org1, called app2.
Now delete the application app1.
Go to app2, try to delete the datasource ds1.
![image](https://user-images.githubusercontent.com/45958978/135600656-05542300-06d6-4139-80de-24d41d3a9073.png)
