### ISSUE TITLE
[Bug] [Deploy Preview-5270] Issues for Widget validation structure 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5465]
List of issues on deploy preview #5270 [Widget property validation structure]

- [ ] 1. [button widget] Evaluated pane is not coming for **Onclick** property 
<img width="489" alt="Screenshot 2021-06-29 at 12 26 14 PM" src="https://user-images.githubusercontent.com/83569920/123751324-3e500f80-d8d5-11eb-8606-02b31d0e9b1b.png">

- [x] 2. The height of the fields for all the 3 property is not same for even single line
<img width="321" alt="Screenshot 2021-06-29 at 11 08 29 AM" src="https://user-images.githubusercontent.com/83569920/123751371-4c9e2b80-d8d5-11eb-89b1-7808656a3306.png">

- [ ] 3. [Chart widget] Only evaluated value is coming for chart type property 
<img width="646" alt="Screenshot 2021-06-29 at 11 02 17 AM" src="https://user-images.githubusercontent.com/83569920/123751469-663f7300-d8d5-11eb-9ecd-a0560c6133fe.png">

- [x] 4. Click on any property > Evaluated pane opens > Expand any property in the evaluated pane > Now move the cursor toward property pane > evaluated pane closes
https://www.loom.com/share/25633419c140404bb4ab30d753992a3c

- [x] 5. [Chart Widget] Expected structure data has “<“ in the series data property 
<img width="325" alt="Screenshot 2021-06-29 at 11 21 35 AM" src="https://user-images.githubusercontent.com/83569920/123751713-a56dc400-d8d5-11eb-990c-56ec781e35f1.png">

- [ ] 6. [Chart Widget] On datapoint click only evaluated value is coming
<img width="670" alt="Screenshot 2021-06-29 at 12 30 44 PM" src="https://user-images.githubusercontent.com/83569920/123751892-d948e980-d8d5-11eb-8273-cbbfc72e957b.png">

- [x] 7. Text size and position on Evaluated pane is different for different property
<img width="304" alt="Screenshot 2021-06-29 at 1 01 06 PM" src="https://user-images.githubusercontent.com/83569920/123911754-cdbef680-d999-11eb-8eab-d9dba29e3d99.png">

- [x] 8. [File Picker]Max file size only shows “evaluated value”
<img width="621" alt="Screenshot 2021-06-29 at 4 42 50 PM" src="https://user-images.githubusercontent.com/83569920/123911607-a0724880-d999-11eb-8ff1-6a17216a1c50.png">

- [ ] 9. [File Picker] Allow file type expected structure looks very weird - can we make it look better
<img width="637" alt="Screenshot 2021-06-30 at 11 55 00 AM" src="https://user-images.githubusercontent.com/83569920/123911968-170f4600-d99a-11eb-8426-c75b430d9cc9.png">

- [x] 10. [Select widget] Filterable property shows only evaluated value
<img width="697" alt="Screenshot 2021-06-30 at 11 56 24 AM" src="https://user-images.githubusercontent.com/83569920/123912094-3ad28c00-d99a-11eb-9e34-fe3c5bcb3220.png">

- [x] 11. [iFrame] Source for iframe expect string and not url - As per the tooltip we should pass URL (Please confirm this)
<img width="301" alt="Screenshot 2021-06-29 at 5 10 42 PM" src="https://user-images.githubusercontent.com/83569920/123911529-88022e00-d999-11eb-8065-446b35487497.png">

**Comment by riodeuno** [comment]
@vivekverma2312 Thanks for reporting these. I'm working on the fixes.

**Comment by riodeuno** [comment]
@vivekverma2312 5. is expected, as it is how typescript signifies the contents of the array. I've added the closing `>` in the latest update.

**Comment by vivekverma2312** [comment]
@riodeuno Issues 4 still exist
12. Only evaluated value is coming for chart type property, on prod we have Expected data type
<img width="783" alt="Screenshot 2021-07-15 at 11 24 26 AM" src="https://user-images.githubusercontent.com/83569920/125736099-3dff45f5-a62b-4110-9e7b-3cebebe04157.png">

**Comment by YogeshJayaseelan** [comment]
@riodeuno observed few more issues please find the details below

13. Image widget - The Expected structure for image field is 'base64 encoded image | data uri | image url' but the expected structure for Default image field is 'String' - **Same behaviour in prod**

<img width="1280" alt="Screenshot 2021-07-15 at 11 49 19 AM" src="https://user-images.githubusercontent.com/35128442/125738770-6b9e369f-c31e-45ba-a582-444968568014.png">


14.List Widget - Background field - shows only expected value - expected structure and example are missing - **Same behaviour in prod**

<img width="1280" alt="Screenshot 2021-07-15 at 11 51 57 AM" src="https://user-images.githubusercontent.com/35128442/125739013-50e63f99-85e9-418c-b744-ae7f39a825d9.png">


15.List Widget - Item Background field - shows only expected value - expected structure and example are missing - **Same behaviour in prod**

<img width="1280" alt="Screenshot 2021-07-15 at 11 53 37 AM" src="https://user-images.githubusercontent.com/35128442/125739114-8138844e-12bd-4a10-a179-61da4b805bcf.png">

16.List Widget - visible JS - Only Expected value is displayed - Expected Structure and Expected Example are missing - **On Prod we have expected data type**

<img width="1280" alt="Screenshot 2021-07-15 at 11 56 01 AM" src="https://user-images.githubusercontent.com/35128442/125739320-37ef35b1-903c-4c52-ae0d-4c3c1f44e4b4.png">

17.Map widget - Initial location - Only Expected value is displayed - Expected Structure and Expected Example are missing - **Same behaviour in prod**

<img width="1280" alt="Screenshot 2021-07-15 at 11 57 26 AM" src="https://user-images.githubusercontent.com/35128442/125739457-c9210804-f62c-489c-bad1-51dfb4d52405.png">

18.Rate widget - Tool tips - Default Expected example is not available 

<img width="1280" alt="Screenshot 2021-07-15 at 11 58 59 AM" src="https://user-images.githubusercontent.com/35128442/125739680-b0022a53-59f2-42a3-abcd-4f721e3ac670.png">

19. Table Widget - Table Data - Clicking on table data field and expanding/clicking on any of the expected property types 'ReferenceError: fetch_users not defined' error occurs - **same behaviour in prod** 

<img width="1280" alt="Screenshot 2021-07-15 at 12 00 02 PM" src="https://user-images.githubusercontent.com/35128442/125739983-54e415f5-f0fb-4c7d-8b7c-c50475daedaa.png">

20. video widget - URL - The expected type should be URL instead of string - **same behaviour in prod**

<img width="1280" alt="Screenshot 2021-07-15 at 12 02 45 PM" src="https://user-images.githubusercontent.com/35128442/125740153-1a3c1b5b-9d06-495e-aba1-c93a2356be34.png">

21. All Widget - If the widget property pane is placed at the bottom area of canvas and when the user expands any of the expected property type the expected property type goes beyond the canvas 

https://loom.com/share/518e672ee1704d70a0ce6d223245976f

**Comment by riodeuno** [comment]
@YogeshJayaseelan Thanks for reporting these, I'll try to get these resolved asap.

**Comment by riodeuno** [comment]
@YogeshJayaseelan I've fixed all except for 19. This is an issue which should be fixed separately, can you create an issue for this?

**Comment by YogeshJayaseelan** [comment]
@riodeuno Created separate issue for 19 - #5925

**Comment by YogeshJayaseelan** [comment]
@riodeuno Retested the fixes for issues 4,12,13,14,15,16,17,18,19,20,21 and please find the status below

**Issues Fixed:**
12, 13, 14, 15, 16, 17, 20

**Issues still exists:**
4)Click on any property > Evaluated pane opens > Expand any property in the evaluated pane > Now move the cursor toward property pane > evaluated pane closes - **This still exists**
https://www.loom.com/share/25633419c140404bb4ab30d753992a3c

18) Rate widget - Tool tips - Default Expected example is not available - **This is still exists and now click or expanding the tool tip expected type property the following error message occurs 'This value does not evaluate to type "Array".**

<img width="1280" alt="Screenshot 2021-07-17 at 12 52 18 PM" src="https://user-images.githubusercontent.com/35128442/126029757-94ee22f5-3a16-49a0-b03b-40f18c988d2b.png">

19. We have raised separate issue for this - #5925 

21. All Widget - If the widget property pane is placed at the bottom area of canvas and when the user expands any of the expected property type the expected property type goes beyond the canvas - **This still exists**
https://loom.com/share/518e672ee1704d70a0ce6d223245976f

**Comment by riodeuno** [comment]
@YogeshJayaseelan 18. Is something we donot support at the moment. I'll look into 20, and 4.

**Comment by riodeuno** [comment]
@YogeshJayaseelan I'm unable to reproduce 20. In the latest update. Let's discuss this tomorrow.

**Comment by YogeshJayaseelan** [comment]
@riodeuno Verified the fixes and found issue 4 and 18 still exists 

18 ) The Expected Example is still displayed as empty [] for tooltip field - Rate Widget - **Expected example template is expected**

New issue:

21) Expected property is not displayed for - OnPageChange field - Table Widget - **In production we have expected property** 

<img width="1680" alt="Screenshot 2021-07-22 at 12 26 06 PM" src="https://user-images.githubusercontent.com/35128442/126600674-9d928504-4bb0-4099-9594-4fb78f53f4d1.png">

**Comment by riodeuno** [comment]
Hi @YogeshJayaseelan Updates:
4. I cannot reproduce this issue. 

Uploading Screen Recording 2021-07-22 at 10.46.02 PM.mov…

21. I don't see it on app.appsmith.com
<img width="624" alt="Screenshot 2021-07-22 at 10 48 09 PM" src="https://user-images.githubusercontent.com/103687/126681286-3d4e5f74-1e34-4dff-9a4b-faec8b4113b0.png">

18. Will be fixed in the the latest update.

**Comment by YogeshJayaseelan** [comment]
@riodeuno Verified the fixes and they are working as expected.

Raised separate issue for point 4 - #6093
