### ISSUE TITLE
[Bug]: Action fails when params have EOF characters inside them

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8802]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ac4b5981f2744d1b8ffebcfd642121ea-00001.gif)](https://www.loom.com/share/ac4b5981f2744d1b8ffebcfd642121ea)

```
Original Binding : "((currentItem) => { navigateTo(currentItem.PRODUCTS_ID, {},'NEW_WINDOW')})(JSON.parse('{"PRODUCTS_ID":"https://snipinternet.my.salesforce.com/0011Q00002PAJShQAP                ","PRODUCTS_NAME":"https://snipinternet.my.salesforce.com/5001Q00001GgPuHQAV","PRODUCTS_DESC":"a\nb\nc","PRODUCTS_COST":"","PRODUCTS_STOCK":"","PRODUCTS_CATEGORY":"","rowIndex":"0"}'))"

```

When a value has `\n` in that case `JSON.parse` seems to fail which in the end cause `navigateTo` to fail.

### Steps To Reproduce

This is a sheet link that has demo data where it is reproducible.  https://docs.google.com/spreadsheets/d/1uRnnqyi44h3qtndthbIAMrPsMB6Mm25tVGu-u0sRess/edit?usp=sharing

1. Add a List Widget
2. Connect Data in which one of the value containes `\n`
3. Add a button to list widget template
4. Add onClick `{{navigateTo(currentItem.SOME_KEY, {},'NEW_WINDOW')}}`
5. See the error

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
verify if this is already solved with unescape

**Comment by Rishabh-Rathod** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/8802?planning-poker) with ZenHub @ajinkyakulkarni @ApekshaBhosale @hetunandu @ohansFavour

**Comment by Rishabh-Rathod** [comment]
This issue is still present after unescape, verified both in release and production.

**Comment by nidhi-nair** [comment]
This use case requires smart substitution to be turned on since the input text needs to be escaped for the new lines to be used in the request. We do need an improvement in UX for users to be told when smart substitution is the solve for a problem, but I'll be closing this issue and we can tackle that separately.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair smart substitution is only for the request right? Here it seems the response is not escaped

**Comment by nidhi-nair** [comment]
IIUC, the repro for this was to run the update query with the reference from the update form widgets. The text field contains a `\n` that was causing the update query to fail. @Rishabh-Rathod was there something other than this that I am missing?

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair no, the sheet has the \n in the PRODUCTS_ID column and that is returned to the list widget. The button is bound to currentItem.PRODUCTS_ID
