### ISSUE TITLE
[Bug]: The value in Default and Placeholder input-box is not restricted to 2 decimal when currency is restricted to 2 decimal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the input widget when the user restrict the  decimal point the default value and the placeholder value should be restricted the same as the Decimal point
![image](https://user-images.githubusercontent.com/45958978/145827619-4c222231-8ac6-422e-8321-f4f879addd48.png)

### Steps To Reproduce

1. GO to canvas
2. Drag and drop the input widget
3. Select Data type as currency 
4. Now restrict decimal to 2 
5. Now Try to add a default value and placeholder value
6. The values should be restricted to 2 decimal point

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
Fixed as part of #9119

**Comment by chandannkumar** [comment]
Decimal value in Placeholder is still not restricted to selected Decimals

![image](https://user-images.githubusercontent.com/95341241/150964639-b3a9bd3e-4163-44b8-82fa-1b784bbebb4e.png)

**Comment by sbalaji1192** [comment]
@chandannkumar Not a valid issue. Placeholder accepts a textual value. There is no value addition in searching for numbers in the placeholder text and restricting the decimal points based on the chosen decimal value. The placeholder is only used for visuals.

Closing this.
